"""add master_products table

Revision ID: 43db1a0a5db1
Revises: c54b23859f49
Create Date: 2026-03-19 13:32:16.987945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43db1a0a5db1'
down_revision: Union[str, None] = 'c54b23859f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ean', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('suggested_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_master_products_description_trgm', 'master_products', ['description'], unique=False)
    op.create_index(op.f('ix_master_products_ean'), 'master_products', ['ean'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_products_ean'), table_name='master_products')
    op.drop_index('ix_master_products_description_trgm', table_name='master_products')
    op.drop_table('master_products')
    # ### end Alembic commands ###
