"""initial schema with license release tenant

Revision ID: 4c438445cb7a
Revises: 
Create Date: 2026-03-18 04:42:03.149172
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c438445cb7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_version'), 'releases', ['version'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('VET', 'SUPPLIER', 'BOTH', name='tenanttype'), nullable=False),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.add_column('licenses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('licenses', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('licenses', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('licenses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('licenses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('licenses', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('licenses', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('licenses', 'updated_at')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_releases_version'), table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
