"""remove_both_tenant_type_and_unique_constraints

Revision ID: 828ae36ceecd
Revises: d17041b7b22b
Create Date: 2026-03-19 15:57:36.105597
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828ae36ceecd'
down_revision: Union[str, None] = 'd17041b7b22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tenants_tax_id_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_unique_constraint(op.f('tenants_tax_id_key'), 'tenants', ['tax_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
