"""license_expand_fields_and_pending_actions

Revision ID: c54b23859f49
Revises: 4c438445cb7a
Create Date: 2026-03-18 18:20:10.511743
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54b23859f49'
down_revision: Union[str, None] = '4c438445cb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hardware_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_pending_actions_hardware_id'), 'pending_actions', ['hardware_id'], unique=False)
    op.add_column('licenses', sa.Column('client_email', sa.String(length=255), nullable=True))
    op.add_column('licenses', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('licenses', sa.Column('company_email', sa.String(length=255), nullable=True))
    op.add_column('licenses', sa.Column('company_tax_id', sa.String(length=30), nullable=True))
    op.add_column('licenses', sa.Column('plan', sa.String(length=20), nullable=False, server_default='MONTHLY'))
    op.add_column('licenses', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('licenses', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('licenses', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('licenses', 'notes')
    op.drop_column('licenses', 'plan')
    op.drop_column('licenses', 'company_tax_id')
    op.drop_column('licenses', 'company_email')
    op.drop_column('licenses', 'company_name')
    op.drop_column('licenses', 'client_email')
    op.drop_index(op.f('ix_pending_actions_hardware_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    # ### end Alembic commands ###
