"""add supplier_products orders order_items

Revision ID: d17041b7b22b
Revises: 43db1a0a5db1
Create Date: 2026-03-19 13:53:11.190320
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17041b7b22b'
down_revision: Union[str, None] = '43db1a0a5db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_tenant_id', sa.Integer(), nullable=False),
    sa.Column('supplier_tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PLACED', 'QUOTED', 'ACCEPTED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quoted_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplier_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['supplier_tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_tenant_id'), 'orders', ['buyer_tenant_id'], unique=False)
    op.create_index(op.f('ix_orders_supplier_tenant_id'), 'orders', ['supplier_tenant_id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_available', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_products_ean'), 'supplier_products', ['ean'], unique=False)
    op.create_index(op.f('ix_supplier_products_tenant_id'), 'supplier_products', ['tenant_id'], unique=False)
    op.create_index('ix_supplier_products_tenant_sku', 'supplier_products', ['tenant_id', 'sku'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quoted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_index('ix_supplier_products_tenant_sku', table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_tenant_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_ean'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_orders_supplier_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_tenant_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
