# Generated by Django 5.2.10 on 2026-01-30 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(help_text='Ej: Vómitos, Vacunación, Control', max_length=200)),
                ('anamnesis', models.TextField(blank=True, verbose_name='Anamnesis / Observaciones')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento / Indicaciones')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en KG', max_digits=5, null=True)),
                ('proxima_visita', models.DateField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='historias_clinicas/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='clinical.historial')),
            ],
        ),
    ]
