"""
Django settings for vetcore project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Leemos el modo. Si no existe, asumimos que es DESKTOP (Cliente Local)
DEPLOYMENT_MODE = os.environ.get('DEPLOYMENT_MODE', 'DESKTOP').upper()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gl!d)td)ccdgnu6v0c^24pu=5p@9^jo)!9d0g4m#9sn4&&zkf8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',   # <--- ¡VERIFICA QUE ESTA LINEA ESTÉ AQUÍ!
    'corsheaders',      # (Opcional por ahora, pero buena práctica)
    # Mis Apps
    'core',
    'inventory',
    'sales',
    'clinical.apps.ClinicalConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.LicenseCheckMiddleware', 
]

ROOT_URLCONF = 'vetcore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vetcore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEPLOYMENT_MODE == 'SAAS':
    # --- FUTURO: MODELO SAAS (NUBE) ---
    # Aquí sí usamos PostgreSQL porque habrá miles de veterinarias en una sola DB
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'vetcore_db'),
            'USER': os.environ.get('DB_USER', 'vetcore_user'),
            'PASSWORD': os.environ.get('DB_PASS', 'vetcore_pass'),
            'HOST': os.environ.get('DB_HOST', 'db'), # Host de Docker
            'PORT': '5432',
        }
    }
    SESSION_COOKIE_NAME = 'sessionid_saas'
    CSRF_COOKIE_NAME = 'csrftoken_saas'
else:
    # --- ACTUAL: MODELO ESCRITORIO (LOCAL/OFFLINE) ---
    # Usamos SQLite tanto en Windows como en tu Docker de desarrollo.
    # Esto garantiza que tu entorno de desarrollo sea IDENTICO al del cliente.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    SESSION_COOKIE_NAME = 'sessionid_desktop'
    CSRF_COOKIE_NAME = 'csrftoken_desktop'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# 1. Cambiamos el código de idioma a Español de Argentina
LANGUAGE_CODE = 'es-ar'

# 2. Cambiamos la zona horaria a la de Córdoba/Argentina
# (Esto es importante para que el cierre de caja corte a las 00:00 de acá y no de Londres)
TIME_ZONE = 'America/Argentina/Cordoba'

# 3. Activamos el sistema de traducción
USE_I18N = True

# 4. Permitimos que Django formatee fechas y números según la región (es-ar)
# (Ej: Usar coma para decimales en lugar de punto, día antes que mes, etc.)
USE_L10N = True

# 5. Soporte para Zona Horaria (Recomendado True para guardar en UTC en la DB y mostrar local al usuario)
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURACIÓN DE LOGIN ---
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'  # Al loguearse, va al Home
LOGOUT_REDIRECT_URL = '/login/'  # Al salir, vuelve al login

# --- CONFIGURACIÓN DE ARCHIVOS MEDIA (Imágenes, PDF) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
