# Generated by Django 5.2.10 on 2026-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto Físico (Control de Stock)'), ('SERVICIO', 'Servicio (Mano de obra, Cirugía, etc)')], default='PRODUCTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
